<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="Addition" Id="{ca5bb83e-67c1-4b69-8987-c478e100429d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Addition : INT
VAR_INPUT
	a : INT;
	b : INT;
END_VAR


VAR_OUTPUT
	result : INT;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[result:= a+b;
Addition := result;

]]></ST>
    </Implementation>
    <LineIds Name="Addition">
      <LineId Id="12" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="47" Count="0" />
      <LineId Id="49" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>