<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Addition" Id="{82be4ab2-16b4-4ec1-8c5c-354222b84c64}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Addition
VAR_INPUT
	num1 : INT;
	num2 : INT;
END_VAR
VAR_OUTPUT
	result : INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="mAdd" Id="{7964930c-b6af-4dc7-b12b-147f9186f591}">
      <Declaration><![CDATA[METHOD public mAdd ]]></Declaration>
      <Implementation>
        <ST><![CDATA[result := num1 + num2;
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Addition">
      <LineId Id="17" Count="0" />
    </LineIds>
    <LineIds Name="FB_Addition.mAdd">
      <LineId Id="5" Count="0" />
      <LineId Id="11" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>