<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{a642ecd4-366a-4aee-ab93-a7b44f42347a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	testAddition : TEST_FB_Addition;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="9" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>